// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCIqzW3mn8WNY3Oiy7fTjS77malfzxobkc',
    appId: '1:349872482331:web:1e03fda9af0aa5e8edf0be',
    messagingSenderId: '349872482331',
    projectId: 'shom-gn',
    authDomain: 'shom-gn.firebaseapp.com',
    storageBucket: 'shom-gn.firebasestorage.app',
    measurementId: 'G-ZZEZM7089S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_PHXuH8kjG7ipacGof_KgSMQofX_y0OE',
    appId: '1:349872482331:android:96a41b854867d54cedf0be',
    messagingSenderId: '349872482331',
    projectId: 'shom-gn',
    storageBucket: 'shom-gn.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCXGLYD3P07_YfAYoE9PHQ3dK3N9T389Q',
    appId: '1:349872482331:ios:98a08ebf893539e3edf0be',
    messagingSenderId: '349872482331',
    projectId: 'shom-gn',
    storageBucket: 'shom-gn.firebasestorage.app',
    iosBundleId: 'com.example.shomGn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCXGLYD3P07_YfAYoE9PHQ3dK3N9T389Q',
    appId: '1:349872482331:ios:98a08ebf893539e3edf0be',
    messagingSenderId: '349872482331',
    projectId: 'shom-gn',
    storageBucket: 'shom-gn.firebasestorage.app',
    iosBundleId: 'com.example.shomGn',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCIqzW3mn8WNY3Oiy7fTjS77malfzxobkc',
    appId: '1:349872482331:web:301add7ef68dc794edf0be',
    messagingSenderId: '349872482331',
    projectId: 'shom-gn',
    authDomain: 'shom-gn.firebaseapp.com',
    storageBucket: 'shom-gn.firebasestorage.app',
    measurementId: 'G-F7E4YJBWFL',
  );
}
